feat: check for compose.ya(m)l file in directory

diff --git a/composectl b/composectl
--- a/composectl
+++ b/composectl
@@ -48,8 +48,8 @@ fi
 
 if test "$DIR" && test "$DIR" != "*"; then
   DIR="$(readlink -f -- "$DIR")"
-  if ! test -d "$DIR"; then
-    printf 'Error: Directory "%s" does not exit\n' "$DIR" >&2
+  if ! test -d "$DIR" || ! (test -f "$DIR/compose.yaml" || test -f "$DIR/compose.yml"); then
+    printf 'Error: Directory "%s" does not contain a compose file\n' "$DIR" >&2
     exit 1
   fi
   INSTANCE="$(systemd-escape -p "$DIR")"
